name: Release builds

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system deps (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          python scripts/build.py --target macos --clean
          cd dist
          zip -9 ../HandLaunch-mac.zip HandLaunch

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          python scripts/build.py --target windows --clean
          Copy-Item "dist/HandLaunch.exe" -Destination "../HandLaunch-win.exe"

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python scripts/build.py --target linux --clean
          cd dist
          tar -czf ../HandLaunch-linux.tar.gz HandLaunch

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            HandLaunch-mac.zip
            HandLaunch-win.exe
            HandLaunch-linux.tar.gz
          fail_on_unmatched_files: false
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


